%% Diagram: Cloudfront Lambda Edge Flow Viewer Request Handles User Identification And Bucke
%% Type: sequence
%%{init: {'htmlLabels': false}}%%
sequenceDiagram
    participant U as User
    participant CF
    participant VR as ViewerReq
    participant OR as OriginReq
    participant VRs as ViewerResp
    participant SSG
    participant SSR

    U->>CF: req + cookies
    CF->>VR: trigger
    VR->>VR: read userId
    VR->>VR: bucket
    VR->>CF: add header
    CF->>OR: trigger
    OR->>OR: read header
    alt ssr
        OR->>SSR: override
        SSR-->>CF: resp
    else ssg
        OR->>SSG: override
        SSG-->>CF: resp
    end
    CF->>VRs: trigger
    VRs->>VRs: set cookies
    VRs-->>U: response
